[project]
name = "watcher"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.16",
    "loguru>=0.7.3",
    "openai>=1.59.7",
    "pywikibot>=9.6.1",
]
